build
bloomberg/memray pull request #673
Opened 2024-09-03 12:05 UTC by pablogsal

- **Try to respect RPATHS of calling dlopen modules with dlinfo**
- **Use scikit-build-core**

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

2024-09-07 01:14 UTC, godlygeek commented on src/memray/_memray.pyx
> +from memray._thread_name_interceptor import ThreadNameInterceptor
Something about how `scikit-build-core` does editable installs is causing this to be necessary... Things work fine with a non-editable install without these changes, but not with an editable install.

2024-09-07 01:24 UTC, godlygeek commented on src/memray/_memray.pyx
> +from memray._thread_name_interceptor import ThreadNameInterceptor
Ah, presumably this:

> The default `editable.mode`, "redirect", uses a custom redirecting finder to combine the static CMake install dir with the original source code.

It's probably winding up wrong about what its package is due to that...

2024-09-07 01:32 UTC, godlygeek commented on src/memray/_memray.pyx
> +from memray._thread_name_interceptor import ThreadNameInterceptor
But somehow it's working for `memray._test_utils`, which _also_ does
```py
from ._destination import Destination
```
Hm, there's still something I don't understand here...

2024-09-07 04:27 UTC, godlygeek commented on src/memray/_memray.pyx
> +from memray._thread_name_interceptor import ThreadNameInterceptor
Ah, the thing that's throwing it off is that there's both a `memray/_memray/` directory and a `memray._memray` module, and they're not the same. I think this is a bug in `scikit-build-core`'s editable mode. I'll try to whip up an MRE to report the bug to them when I can. It should be easy to demonstrate that `__package__` changes depending on whether or not the install is editable.

2024-09-17 22:56 UTC, godlygeek commented on src/memray/_memray.pyx
> +from memray._thread_name_interceptor import ThreadNameInterceptor
That's been fixed in scikit-build-core 0.10.6

2025-04-29 19:38 UTC, godlygeek commented
This is missing the `npm install` and `npm run-script build` steps, I think

2026-07-11 14:14 UTC, pablogsal commented
I rebased  and fixes all the other issues

2026-07-11 17:46 UTC, pablogsal commented
@godlygeek this is ready can you approve?

2026-07-11 19:37 UTC, godlygeek requested changes
Just a few small things:

The `setup.py` used to run `npm install` and `npm run-script build` if `src/memray/reporters/templates/assets/*.js` didn't exist. The CMakeLists.txt never does that. Is that an intentional omission? Is the assumption that, because these files are checked into source control, we should never encounter the situation where they're missing, and so what was in the `setup.py` was dead code?

And, on a separate note: if we're removing the `MANIFEST.in`, we should also remove the `setup.py`, shouldn't we? Is there a reason to keep it?

2026-07-11 19:37 UTC, godlygeek commented on src/memray/commands/_attach.gdb
> +set $result = (int)access($libpath, 4)
I don't understand this change. Is `scikit-build-core` sometimes creating shared libraries that don't have the executable bit set? If so, I can't reproduce that... What circumstances does it do that under?

2026-07-11 19:37 UTC, godlygeek commented on pyproject.toml
> +  "setuptools",
```suggestion
  "scikit-build-core",
```

2026-07-11 19:37 UTC, godlygeek commented on pyproject.toml
> +  "setuptools",
```suggestion
  "scikit-build-core",
```

2026-07-11 19:37 UTC, godlygeek commented on pyproject.toml
>  test=['Cython', 'coverage[toml]', "greenlet; python_version < '3.15'", 'pytest', 'pytest-cov', 'ipython', 'setuptools', 'pkgconfig', 'pytest-textual-snapshot', 'textual >= 0.43, != 0.65.2, != 0.66',
```suggestion
test=['Cython', 'coverage[toml]', "greenlet; python_version < '3.15'", 'pytest', 'pytest-cov', 'ipython', 'scikit-build-core', 'pkgconfig', 'pytest-textual-snapshot', 'textual >= 0.43, != 0.65.2, != 0.66', 'packaging']
```

2026-07-11 21:09 UTC, pablogsal commented
Done. I removed `setup.py`, updated ASV, and verified all checked-in JS assets in the sdist/wheel and the regeneration stuff. I added `scikit-build-core` but kept `setuptools` because the integration fixtures still use `setup.py`/`distutils`.

2026-07-11 21:17 UTC, pablogsal commented on src/memray/commands/_attach.gdb
> +set $result = (int)access($libpath, 4)
You are right: this is not a `scikit-build-core` behavior. CMake, the wheel, and a clean UV 3.14 editable install all keep the execute bit. The rebased UV and coverage jobs failed at this guard, but their logs did not record the file mode. The actual issue is that `5` checks `R_OK | X_OK`, while the guard only needs readability; I verified `dlopen` succeeds on a `0644` library. This is an unrelated forward-port fix.

2026-07-11 21:26 UTC, godlygeek commented
> kept `setuptools` because the integration fixtures still use `setup.py`/`distutils`

Ah, right, makes sense

2026-07-11 22:33 UTC, godlygeek approved these changes
LGTM. I copied the big comment about our TLS model hackery over from the setup.py into the CMakeLists.txt, and squashed a few of these commits together. I left the ones that were fixing separate issues that were merely unearthed by the build backend change un-squashed.

2026-07-11 23:19 UTC, merged

2026-07-12 01:18 UTC, godlygeek commented on src/memray/commands/_attach.gdb
> +set $result = (int)access($libpath, 4)
Ah, I see what caused this. https://github.com/bloomberg/memray/pull/959 fixes it. Though I've left your change in place, since you're right, we only need `R_OK` and not `R_OK | X_OK`, but I've figured out why the `x` bit wasn't (always?) getting set, and it's an easy fix.